project_identifier: wirecom
base_path: .

files:
  -
    source: '/locales/en/translation.json'
    translation: '/locales/%two_letters_code%/translation.json'
    update_option: 'update_as_unapproved'
