project_identifier: wirecom
base_path: .

files:
  -
    source: '/dist/locales/en/translation.json'
    translation: '/dist/locales/%two_letters_code%/translation.json'
    update_option: 'update_as_unapproved'
