branch-defaults:
  express-migration:
    environment: wire-account-dev
deploy:
  artifact: dist/wire-account.zip
global:
  application_name: Account
  default_platform: Node.js
  default_region: eu-west-1
  sc: git
  workspace_type: Application
